import "./globals.css";
import type { Metadata } from "next";
import { Alegreya, Inter } from "next/font/google";
import { Manrope, Marck_Script } from "next/font/google";
import "yet-another-react-lightbox/styles.css";
import { Toaster } from "react-hot-toast";
const manrope = Manrope({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin-ext", "vietnamese", "latin"],
  variable: "--font-manrope",
});

const marck = Marck_Script({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-marck",
});
const alegreya = Alegreya({
  subsets: ["latin-ext", "vietnamese", "latin"],
  weight: ["400", "500", "700", "800", "900"],
  variable: "--font-alegreya",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={` ${marck.variable} ${manrope.variable} 
        ${alegreya.variable}
      font-manrope `}
      >
        <Toaster />
        {children}
      </body>
    </html>
  );
}
